### PR TITLE
Allow passing a priority to inmain and inmain_later as `_priority` kwarg

### PR DESCRIPTION
**Pull request by chrisjbillington**
Allow passing through the priority for posting an event via qtutils functions.

Prepend the arg with an underscore to decrease the odds of a collision with actual keyword arguments the user might be passing to their function, since they will all be lumped in together the way that things are currently organised.

### CODE REVIEW

**Comment by philipstarkey** [comment]
Completely off-topic, but do pull requests share IDs with issues? I hadn't imported the issues over yet...which means when we do move them over, references to issues in other messages will be wrong!

Should we fix this now while we have the chance?

**Comment by chrisjbillington** [comment]
I believe they do share IDs! They'll all be off by one.

What would fixing now entail? Deleting and re-making the repo? Up to you, I can just re-make a pull request.

**Comment by philipstarkey** [comment]
Ok, I've renamed this repo and re-created the repository cleanly by importing from Github to Github (apparently that works and won't be attached to this one like forking would be!). I've also now migrated the issues as best as we can (I think I held off doing this before because I'm working on a bitbucket export tool, but it's not worth waiting for that to be done for this. We should be able to use it for the labscript suite though!)

Can you re-fork the new qtutils repo, push your changes to that and then make a new pull request to the new repo?
Once that is done I'll delete this repo!

**Comment by chrisjbillington** [comment]
Since the event priorities don't solve the camera hanging problem, I'm thinking I'll just not make the PR, does that sound good, or do you think it's worth including anyway? It has never come up in any other context. If you don't care about including this code then just delete the repo and I'll re-fork next time I need to do something.

**Comment by chrisjbillington** [comment]
Closing this to get it out of my list of outstanding PRs

Can revisit if we find it to be necessary in future.

**Pull request closed without merging**
